# Numpy

Numerical Python!<br>
Numpy is used to create homogeneous multidimensional array<br>
NumPy dimensions are called axes.<br>

In [2]:
import numpy as np
#The arange function:

#numpy.arange([start, ]stop, [step, ]dtype=None)
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [5]:
import numpy as np

a = np.arange(0,20,0.5,dtype=np.float32).reshape(5, 8)

print(a,"\n")

#Number of dimensions
print("ndim:", a.ndim,"\n")

#Shape or dimensions
print("shape:", a.shape,"\n")

#Data Type of elements
print("dtype:", a.dtype.name,"\n")

#No of bytes required for each element
print("item size:",a.itemsize,"\n")

#Number of elements
print("size:",a.size,"\n")

#Data type of the array
print("type of a:",type(a),"\n")


[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10.  10.5 11.  11.5]
 [12.  12.5 13.  13.5 14.  14.5 15.  15.5]
 [16.  16.5 17.  17.5 18.  18.5 19.  19.5]] 

ndim: 2 

shape: (5, 8) 

dtype: float32 

item size: 4 

size: 40 

type of a: <class 'numpy.ndarray'> 



In [6]:
#Some Useful functions:

print("\nZeros:\n",np.zeros((3, 4)))
print("\nOnes:\n",np.ones((3, 4)))
print("\nOnes_like:\n",np.ones_like(a))
print("\nZeros_like:\n",np.zeros_like(a))


Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Ones_like:
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Zeros_like:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
#Arithmetic Operators:

a = np.array([0,1,2,3])
b = np.arange(4)
print("\n Array a:",a)
print("\n Array b:",b)

#Not inplace
#BROADCASTING
b = b+1
print("\n Array b+1:",b)

b -= 1
print("\n Array b+1-1:",b)

c = b**2
print("\n Array b^2(element-wise):",c)

print("\n Elementwise equality check for List:",a == [0,1,2,4])

print("\n Elementwise equality check for List:",[0,1,2,3] == [0,1,2,4])

print("\n Elementwise equality check for Array:",np.array([1,3])==np.array([1,2]))



 Array a: [0 1 2 3]

 Array b: [0 1 2 3]

 Array b+1: [1 2 3 4]

 Array b+1-1: [0 1 2 3]

 Array b^2(element-wise): [0 1 4 9]

 Elementwise equality check for List: [ True  True  True False]

 Elementwise equality check for List: False

 Elementwise equality check for Array: [ True False]


In [5]:
#Matrix Operations:

A = np.array([[1,2],[3,4]])

B = A*2

print("\nThe original matrix A:")
print(A)

print("\nThe original matrix B:")
print(B)

print("\nAdd two matrix (A+B)")
print(np.add(A,B))

print("\nHadamard product (element wise or Schur product): A*B:")
print(A * B)                       # elementwise product

print("\nUsual matrix multiplication 1:")
print(A @ B)                       # matrix product.

print("\nUsual matrix multiplication 2:")
print(A.dot(B))                    # another matrix product


The original matrix A:
[[1 2]
 [3 4]]

The original matrix B:
[[2 4]
 [6 8]]

Add two matrix (A+B)
[[ 3  6]
 [ 9 12]]

Hadamard product (element wise or Schur product): A*B:
[[ 2  8]
 [18 32]]

Usual matrix multiplication 1:
[[14 20]
 [30 44]]

Usual matrix multiplication 2:
[[14 20]
 [30 44]]


In [7]:
#Slicing and creating views:

a = np.arange(10)**3
print("\nOriginal Array:")
print(a)

print("\nShowig a slice Array from 2 to 4:")
print(a[2:5])

print("\nShowing elements in steps of 3 starting with 2:")
print(a[2:12:3])

print("\nSet elements 0, 2 and 4 to '1000':")
a[:6:2] = 1000
print(a)

print("\nPrint entire array in reverse order:")
print(a[ : :-1])

print("\nPrint entire array to demonstrate use of '...':")
print(a[...])


Original Array:
[  0   1   8  27  64 125 216 343 512 729]

Showig a slice Array from 2 to 4:
[ 8 27 64]

Showing elements in steps of 3 starting with 2:
[  8 125 512]

Set elements 0, 2 and 4 to '1000':
[1000    1 1000   27 1000  125  216  343  512  729]

Print entire array in reverse order:
[ 729  512  343  216  125 1000   27 1000    1 1000]

Print entire array to demonstrate use of '...':
[1000    1 1000   27 1000  125  216  343  512  729]


In [7]:
# Reshape
# Returns an array containing the same data with a new shape.

arr = np.arange(25)

In [8]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
ranarr = np.random.randint(0,50,10)

In [10]:
ranarr

array([18, 42, 32, 10, 28, 35,  2, 21, 31, 47])

In [11]:
# Min,Max,argmax,argmin
ranarr.max()

47

In [12]:
ranarr.argmax()

9

In [13]:
ranarr.min()

2

In [14]:
ranarr.argmin()

6